build.properties, ivy.xml
Add spark plugin
https://github.com/pentaho/pentaho-kettle/pull/1230
@dkincade
=> [BAD-170] Support for Spark

build-res/subfloor.xml, build.properties, ivysettings.xml
Merge of master into future-develop
=> Auto-Merge refreshing development branch

src/org/pentaho/pms/ui/MetaEditor.java
@pentaho-nbaker, @dkincade, review it please.
The fix is trivial (see the first commit separately).
=> [PMD-1011] - NullPointerException error appears when user trying to delete saved domain

src/org/pentaho/pms/ui/MetaEditor.java
@rmansoor, review it please. 
This is a backport of https://github.com/pentaho/pentaho-metadata-editor/pull/50
=> [SP-2250] - Backport of PMD-1011 - NullPointerException error appears when user trying to delete saved domain (6.0 Suite)

src/org/pentaho/pms/ui/MetaEditor.java
@rmansoor, review it please. This is a backport of https://github.com/pentaho/pentaho-metadata-editor/pull/50
=> [SP-2251] - Backport of PMD-1011 - NullPointerException error appears when user trying to delete saved domain (5.4 Suite)

ivy.xml
http://jira.pentaho.com/browse/BACKLOG-10143
pentaho/big-data-plugin#715
=> [BACKLOG-10143]Remove pdi-spark-plugin

src/org/pentaho/pms/ui/MetaEditor.java
Also fixed the Menu bar issue where it reports the app name as SWT for mac.
_second commit for pre-existing checkstyle violations_
=> [BACKLOG-11192] - PME won't shut down on mac.

ivy.xml
Reverts pentaho/pentaho-metadata-editor#82
=> Revert "[PDI-15059]-Updated slf4j jars to 1.7.22 version in pme"

src/org/pentaho/pms/ui/dialog/PublishDialog.java
- added checking for empty domain name
=> [PMD-1068]-Able to Publish a model with no domain name

package-res/metadata-editor.bat, package-res/metadata-editor.sh, package-res/metadata-editorDebug.bat, package-res/set-pentaho-env.bat, package-res/set-pentaho-env.sh
=> [PSW-229] Script files don't have an header with Copyright data

src/org/pentaho/pms/ui/dialog/PublishDialog.java
- added checking on empty domain name
=> [SP-3605][PMD-1068]-Able to Publish a model with no domain name

src/org/pentaho/pms/ui/dialog/PublishDialog.java
- added checking on empty domain name
=> [SP-3606][PMD-1068]-Able to Publish a model with no domain name

ivy.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12995] update pdi plugins groupId

ivy.xml
=> [BACKLOG-19163] PME (CE) - error to start-up bundle "mvn:org.eclipse.jetty.aggregate"

src/org/pentaho/pms/ui/dialog/BusinessCategoryDialog.java, src/org/pentaho/pms/ui/dialog/BusinessTableDialog.java, src/org/pentaho/pms/ui/dialog/PhysicalTableDialog.java
Reverts pentaho/pentaho-metadata-editor#101
=> Revert "[BISERVER-13338] - Data source domain object mutation while re-parsing"

pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
=> [BACKLOG-13306] GAV change

pom.xml
@pentaho/2-1b 
Depends on https://github.com/pentaho/mql-editor/pull/47
=> [BACKLOG-20450] Downstream update for mql-editor

editor/src/main/java/org/pentaho/pms/ui/MetaEditor.java
The domain name input must be mandatory.
@pamval @duarteteixeira 
@ricardosilva88 @pentaho-lmartins
=> [PMD-1077] CLONE - Able to Publish a model with no domain name

editor/src/main/java/org/pentaho/pms/ui/MetaEditor.java, editor/src/main/java/org/pentaho/pms/ui/dialog/PublishDialog.java
Merge after : https://github.com/pentaho/pentaho-kettle/pull/5807
@bantonio82 @ssamora
=> [SP-4643] Backport of PMD-1077 - CLONE - Able to Publish a model with no domain name (8.1 Suite)

editor/pom.xml, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

assemblies/pme-ce/src/main/resources/Metadata Editor.app/Contents/Info.plist
=> [BACKLOG-26968] Update copyright versions to 2019

assemblies/pme-ce/src/main/resources/Metadata Editor.app/Contents/Info.plist
=> [SP-4856] Backport of BACKLOG-26968 - Update copyright versions to 2019

package-res/Metadata Editor.app/Contents/Info.plist
=> [SP-4857] Backport of BACKLOG-26968 - Update copyright versions to 2019

editor/src/main/java/org/pentaho/pms/ui/security/SecurityDialog.java
=> [PMD-1096] - Security Service contains a typo after pressing Test button

editor/src/main/java/org/pentaho/pms/ui/security/SecurityDialog.java
This PR was a cherry-pick from: https://github.com/pentaho/pentaho-metadata-editor/pull/145
@LeonardoCoelho71950 @ssamora
=> [SP-4886] - Backport of PMD-1096 - Security Service contains a typo after pressing Test button (8.2 Suite)

pom.xml
=> [BACKLOG-27575] Remove Felix Main dependency

assemblies/pme-ce/pom.xml
=> [BACKLOG-27567] Added missing OSGi core dependency

editor/src/main/java/org/pentaho/pms/ui/MetaEditor.java, editor/src/main/java/org/pentaho/pms/ui/util/Splash.java
=> [SP-4985] - Backport of PMD-1028

src/org/pentaho/pms/ui/MetaEditor.java, src/org/pentaho/pms/ui/util/Splash.java
Reverts pentaho/pentaho-metadata-editor#155
=> Revert "[SP-4984] - Backport of PMD-1028"

assemblies/pme-ce/src/main/resources-filtered/metadata-editor.sh
=> [BACKLOG-28797] PME - Console shows many errors when the Database Connection windows opens

assemblies/pme-ce/src/main/resources/metadata-editor.sh
@pentaho/tatooine @bantonio82 @smmribeiro
=> [SP-5084] Backport of PMD-1100 - SWT issue on console "GLib-GObject-CRITICAL" and " GLib-GObject-WARNING" (8.2 Suite)

package-res/metadata-editor.sh
@pentaho/tatooine @bantonio82 @smmribeiro
=> [SP-5092] Backport of PMD-1100 - SWT issue on console "GLib-GObject-CRITICAL" and " GLib-GObject-WARNING" (7.1 Suite)

assemblies/pme-ce/pom.xml, assemblies/pme-ce/src/assembly/assembly.xml
=> [BACKLOG-29564] - PME-CE Assembly- Migrating from deprecated old style

pom.xml
[BACKLOG-31473] Include org.apache.karaf.diagnostic.boot in the assembly
=> [BACKLOG-27590] Upgrade to Karaf 4.2.6

assemblies/pme-ce/src/main/resources/Metadata Editor.app/Contents/Info.plist
@pentaho/millenniumfalcon please review
=> [BACKLOG-34328] - PME app info showing outdated version

assemblies/pme-ce/pom.xml
=> [BACKLOG-35888] Add metastore locator and repository locator kettle

assemblies/pme-ce/pom.xml
=> [PPP-4833] H2-2.1.210 shipped it is currently vulnerable to specify password in cleartext

editor/pom.xml, editor/src/test/java/org/pentaho/pms/ui/MetaEditorTest.java, pom.xml
BACKLOG-39572 UPDATE Java17Compatibility
=> [BACKLOG-39572][UPDATE][Java17Compatibility]

editor/src/main/java/org/pentaho/pms/ui/QueryBuilderDialog.java
=> [PMD-1110] - Query Builder - Examine Preview Data Window - Name of columns does not appear

pom.xml
- adding snakeyaml to pme-ce  libext/pentaho folder
=> [PPP-5163] Vulnerable Component: snakeyaml - part 2 ( Non OSGi upgrade)

editor/src/main/java/org/pentaho/pms/ui/util/Splash.java
- Follow up PR to improve startup splash timer logic on Windows (ensure splash closes after 5s without blocking, allowing the user to close it faster via-click if they wish)
=> [BACKLOG-43118] In Mac Ventura, not able to use PME

editor/src/main/java/org/pentaho/pms/ui/dialog/PublishDialog.java, pom.xml
[BACKLOG-43559]-Upgrading Java EE to Jakarta EE and Jersey libraries in pentaho-metadata-editor
[BACKLOG-43559]: https://hv-eng.atlassian.net/browse/BACKLOG-43559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43559]-Upgrading Java EE to Jakarta EE and Jersey libraries in pentaho-metadata-editor

editor/pom.xml
[BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21
[BACKLOG-43938]: https://hv-eng.atlassian.net/browse/BACKLOG-43938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43938]-Fixing test1 pipeline test failures running on JDK21

pom.xml
=> chore[PPP-5719]: move saxon version to pentaho parent pom

pom.xml
Reverts pentaho/pentaho-metadata-editor#311
=> Revert "chore[PPP-5719]: upgrade Saxon dependency"
